# Generated by Django 5.2.7 on 2025-10-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_created_at_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
    ]
