# Generated by Django 5.0.14 on 2025-10-22 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RESERVED', 'Reservado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_requests', to='destinations.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
