# Generated by Django 5.2.7 on 2025-10-23 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Airline Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Airline Code')),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Logo URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Airline',
                'verbose_name_plural': 'Airlines',
                'db_table': 'airlines',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
