# Generated by Django 5.2.7 on 2025-10-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_type', models.CharField(choices=[('main', 'Principal'), ('companion', 'Acompañante')], db_column='passenger_type', default='main', max_length=20)),
                ('first_name', models.CharField(db_column='first_name', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(db_column='last_name', max_length=100, verbose_name='Apellido')),
                ('country_of_residence', models.CharField(db_column='country_of_residence', max_length=100, verbose_name='País de Residencia')),
                ('identity_document', models.CharField(db_column='identity_document', max_length=50, verbose_name='Documento de Identidad')),
                ('date_of_birth', models.DateField(db_column='date_of_birth', verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], db_column='gender', max_length=1)),
                ('passenger_category', models.CharField(choices=[('adult', 'Adulto'), ('child', 'Niño'), ('infant', 'Infante')], db_column='passenger_category', default='adult', max_length=20)),
                ('seat_number', models.CharField(blank=True, db_column='seat_number', max_length=10, null=True, verbose_name='Número de Asiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Pasajero de Reserva',
                'verbose_name_plural': 'Pasajeros de Reserva',
                'db_table': 'reservation_passengers',
                'ordering': ['passenger_type', 'created_at'],
            },
        ),
    ]
