# Generated by Django 5.2.7 on 2025-10-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation_passengers', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationpassenger',
            name='reservation',
            field=models.ForeignKey(db_column='reservation_id', on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='reservations.reservation'),
        ),
    ]
